name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd backend
        npm install

    - name: Run Development Server
      run: |
        cd backend
        npm run dev &

    - name: Wait for Server to Start
      run: sleep 10

    - name: Run Tests
      run: |
        cd backend
        npm test
